spring:
  application:
    name: temp01
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017
      database: db
      authentication-database: admin
management:
  endpoints:
    access:
      default: read_only
  endpoint:
    health:
      show-details: always
