spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017
      database: db
      authentication-database: admin
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      show-details: always
